const { MongoClient } = require("mongodb");
require('dotenv').config();


const clientDB = new MongoClient(process.env.mongo_connectionstring)


unique_words = []


string_one = "Biodiversity, the intricate web of life on our planet, plays a pivotal role in shaping and sustaining ecosystems It encompasses the rich tapestry of species, genetic diversity, and ecosystems that exist on Earth. Biodiversity is not merely a concept; it is the life force that underpins the survival of all organisms, including humans. The importance of biodiversity in ecosystems cannot be overstated. First and foremost, biodiversity is a source of stability and resilience in ecosystems. Diverse ecosystems are better equipped to withstand environmental changes, such as climate fluctuations or natural disasters. Each species within an ecosystem has a unique role to play, and the loss of any one species can disrupt the delicate balance. The greater the variety of species present, the more likely an ecosystem can adapt to external pressures, ensuring its long-term survival. Biodiversity is also crucial for ecosystem services, which are the benefits that nature provides to humans. These services include the purification of air and water, pollination of crops, and the regulation of climate. For example, bees, butterflies, and other pollinators are responsible for fertilizing many of the plants that produce our food. Without biodiversity, these essential services would be compromised, leading to food scarcity and economic challenges Furthermore, biodiversity is a source of innovation and discovery. Many of the medicines we rely on today have their origins in plant and animal species. The diverse genetic pool found in different species holds the potential for groundbreaking scientific advancements. Protecting biodiversity is not just an ethical imperative; it is also an investment in our future well-being Human activities, such as deforestation, habitat destruction, overexploitation of resources, and pollution, are driving a global decline in biodiversity. Climate change further exacerbates this crisis by altering habitats and making it difficult for species to adapt. Urgent action is needed to reverse these trends and preserve biodiversity for future generations. Conservation efforts include the establishment of protected areas, sustainable resource management practices, and international agreements to combat illegal wildlife trade. Additionally, raising public awareness and education about the importance of biodiversity is crucial in garnering support for conservation initiatives.In conclusion, biodiversity is the lifeblood. "


string_two = "Artificial Intelligence reshaping various aspects of our lives. This rapidly advancing technology, which encompasses machine learning, neural networks, and data analytics, has the potential to revolutionize industries and improve efficiency in countless domains. AI-driven innovations are already being integrated into healthcare, finance, transportation, and more. The impact of AI on society is profound and multifaceted. One of the most noticeable effects of AI is its influence on the job market. Automation and machine learning algorithms have the capability to perform tasks previously done by humans, leading to concerns about job displacement. While AI can enhance productivity and reduce repetitive tasks, it also necessitates the development of new skills and job roles. Education and workforce adaptation are crucial in ensuring that individuals can thrive in an AI-powered economy. Moreover, AI has the potential to revolutionize healthcare. Machine learning algorithms can analyze vast datasets to diagnose diseases, predict patient outcomes, and personalize treatment plans. This has the potential to improve patient care, reduce medical errors, and lower healthcare costs. However, ethical considerations related to data privacy and algorithm biases must be addressed to ensure the responsible and equitable use of AI in healthcare. AI is also transforming transportation through the development of autonomous vehicles. Self-driving cars have the potential to reduce accidents, alleviate traffic congestion, and increase mobility for individuals with disabilities. However, regulatory challenges and safety concerns must be overcome before widespread adoption can occur. In the realm of finance, AI-powered algorithms are used for trading, fraud detection, and risk assessment. These technologies can enhance the efficiency of financial systems but also raise concerns about market stability and the potential for algorithmic trading to amplify financial crises. Additionally, AI's impact extends to environmental sustainability. Machine learning models can analyze environmental data to optimize resource management, predict natural disasters, and mitigate the effects of climate change. AI is a valuable tool in the fight against climate change, helping us make more informed decisions for a sustainable future. In conclusion, Artificial Intelligence is a transformative force that is reshaping our society across various domains. While."


string_three = "Social media has become an integral part of modern society, profoundly influencing how we communicate, connect, and share information. Platforms like Facebook, Twitter, Instagram, and TikTok have transformed the way we interact with one another and consume content. The impact of social media on society is far-reaching and multifaceted. One of the most significant effects of social media is its role in connecting people across the globe. It has broken down geographical barriers, allowing individuals to communicate with friends, family, and acquaintances regardless of their physical location. This interconnectedness has facilitated the exchange of ideas, cultures, and experiences on an unprecedented scale. However, it also raises concerns about privacy and the security of personal information. The collection and use of user data by social media companies have sparked debates about data protection and user consent. Social media has also played a pivotal role in shaping public discourse and activism. It has provided a platform for marginalized voices to be heard, enabling movements like #BlackLivesMatter and #MeToo to gain momentum and effect change. However, the spread of misinformation and the echo chamber effect, where individuals are exposed primarily to viewpoints that align with their own, have challenged the quality of public discourse. Furthermore, social media has had a profound impact on mental health. The constant exposure to curated images and lifestyles can lead to feelings of inadequacy and anxiety, commonly referred to as 'FOMO' (Fear of Missing Out). Cyberbullying and online harassment have also become prevalent issues, affecting the mental well-being of many users, especially young people. Additionally, the addictive nature of social media platforms has raised concerns about screen time and its impact on productivity and real-world social interactions. On the positive side, social media has become a powerful tool for businesses and influencers to reach their target audiences and promote products or ideas. It has democratized marketing and given rise to new forms of online entrepreneurship. Social media's role in disseminating information during emergencies and crises, such as natural disasters or public health emergencies, cannot be understated. In conclusion, social media has had a profound and multifaceted impact on society. While it has connected people, empowered movements, and facilitated."


string_four = "Space exploration has captivated the human imagination for decades and represents one of the most remarkable achievements of science and technology. The exploration of space, including missions to the Moon, Mars, and beyond, has had a profound impact on our understanding of the universe and our place within it. The significance of space exploration extends beyond scientific curiosity; it encompasses technological innovation, international collaboration, and the quest for knowledge. One of the most notable achievements in space exploration was the Apollo 11 mission in 1969, which landed humans on the Moon for the first time. This historic event not only marked a giant leap for humanity but also demonstrated the immense capabilities of human ingenuity and engineering. The subsequent missions to the Moon provided valuable scientific data about the Moon's geology and history, enhancing our understanding of Earth's nearest celestial neighbor. Space exploration has also focused on Mars, with rovers like Curiosity and Perseverance conducting research on the Martian surface. These missions have sought to uncover clues about Mars' past habitability and the potential for life beyond Earth. Additionally, space telescopes like the Hubble Space Telescope have provided breathtaking images of distant galaxies, expanding our knowledge of the cosmos and deepening our sense of wonder about the universe. Space exploration is not limited to any single nation; it represents a global endeavor. International collaboration has been a cornerstone of space exploration, with agencies like NASA, ESA, Roscosmos, and others working together on joint missions and research. The International Space Station (ISS) is a prime example of international cooperation, where astronauts from various countries live and work together in space for extended periods. Beyond its scientific and technological significance, space exploration has practical applications that benefit life on Earth. The development of materials, technologies, and medical research for space missions has often led to innovations that have improved life on our planet. For instance, advancements in water purification and life support systems for space missions have found applications in providing clean drinking water in remote areas and supporting disaster relief efforts. Furthermore, space exploration inspires future generations of scientists, engineers, and dreamers. It fosters a"

string_five = "Renewable energy sources, such as solar, wind, hydro, and geothermal power, have emerged as crucial players in the transition towards a more sustainable and environmentally friendly future. The utilization of renewable energy technologies represents a paradigm shift away from fossil fuels, with profound implications for energy production, climate change mitigation, and global sustainability. The significance of renewable energy extends beyond reducing greenhouse gas emissions; it encompasses economic growth, energy independence, and the preservation of natural ecosystems. One of the most compelling aspects of renewable energy is its environmental benefits. Unlike fossil fuels, renewable energy sources produce little to no greenhouse gas emissions when generating electricity. This reduction in carbon emissions plays a pivotal role in mitigating climate change and curbing the adverse effects of global warming, such as rising sea levels and extreme weather events. Additionally, renewable energy technologies have a significantly lower environmental impact in terms of land use and resource extraction compared to traditional energy sources. The development of solar panels and wind turbines, for example, has become increasingly efficient and sustainable. Renewable energy also offers the potential for greater energy independence. Relying on domestic renewable energy sources reduces a nation's vulnerability to fluctuations in fossil fuel prices and supply disruptions. This energy security can bolster national economies and reduce geopolitical tensions associated with energy resources. Moreover, renewable energy technologies have become increasingly cost-competitive with fossil fuels. The falling costs of solar panels, wind turbines, and energy storage systems have made renewable energy a viable option for homeowners, businesses, and utilities. This economic viability has spurred job creation and economic growth in the renewable energy sector. The transition to renewable energy also fosters innovation and technological advancement. Researchers and engineers continue to develop more efficient and sustainable renewable energy solutions, such as next-generation solar cells and advanced wind turbine designs. Furthermore, renewable energy development often aligns with the preservation of natural ecosystems. Hydropower projects, for instance, can be designed to minimize ecological impacts, and solar installations can be"

string_six = "Climate change poses an increasingly dire threat to coastal communities around the world. Rising sea levels, more frequent and severe storms, and ocean acidification are just a few of the challenges that coastal regions are facing. One of the most pressing concerns is the rise in sea levels due to the melting of polar ice caps and the expansion of seawater as it warms. This phenomenon threatens to inundate low-lying coastal areas, displacing millions of people and causing extensive damage to infrastructure. Coastal erosion is exacerbating the problem, as shorelines retreat, leaving communities vulnerable to storm surges and flooding. In addition to the physical impacts, climate change is disrupting the delicate balance of marine ecosystems. Ocean acidification, caused by increased carbon dioxide absorption by the oceans, is harming marine life, particularly coral reefs and shellfish populations. These ecosystems are not only crucial for biodiversity but also for the livelihoods and food security of coastal communities. Furthermore, more frequent and intense storms, fueled by warmer ocean temperatures, are putting coastal regions at risk of devastating hurricanes, typhoons, and cyclones. These extreme weather events can result in extensive property damage and loss of life. Coastal communities are also grappling with the economic consequences of climate change. Industries such as tourism, fisheries, and agriculture, which rely heavily on coastal areas, are facing disruptions due to changing weather patterns and ecosystem degradation. Despite these challenges, there is hope in the form of adaptation and mitigation measures. Coastal communities are working to implement strategies such as building resilient infrastructure, restoring natural buffer zones like mangroves and dunes, and transitioning to more sustainable practices. Moreover, international efforts to reduce greenhouse gas emissions are crucial in slowing down the rate of global warming and mitigating the impacts on coastal regions. In conclusion, the impact of climate change on coastal communities is profound and multifaceted. Urgent action is needed to address rising sea levels, ocean acidification, and extreme weather events. Adaptation and mitigation efforts, along with global cooperation, are essential to safeguard the well-being and resilience of coastal populations in the face of a changing climate"

string_seven = "Social media platforms have become powerful influencers in shaping political discourse and public opinion in the digital age. The ability to instantly share information, connect with like-minded individuals, and engage in discussions has transformed the way politics is discussed and debated. One of the most significant impacts of social media on political discourse is its role in democratizing information dissemination. Citizens can now access news and updates from a wide range of sources, both mainstream and alternative, allowing for a more diverse and decentralized flow of information. However, this democratization also comes with challenges, as misinformation and fake news can spread rapidly, often blurring the lines between fact and fiction. Social media platforms have also provided a platform for political activism and mobilization. Movements like the Arab Spring and #BlackLivesMatter have used social media to organize protests, raise awareness, and amplify their voices, leading to real-world policy changes. On the other hand, the echo chamber effect, where individuals are exposed primarily to viewpoints that align with their own, can contribute to polarization and hinder constructive dialogue. Moreover, the role of social media in political advertising and micro-targeting has raised concerns about the manipulation of public opinion and the influence of external actors on elections. Regulatory and ethical questions surrounding data privacy and content moderation have become central to the debate on the role of social media in politics. In conclusion, social media has had a profound impact on political discourse, enabling greater access to information, mobilizing political movements, and influencing public opinion. However, it also presents challenges related to misinformation, polarization, and ethical considerations that require ongoing scrutiny and regulation to ensure its responsible and constructive use in the political sphere."


string_eight = "In the digital age, cybersecurity has become a paramount concern, as our reliance on technology and the internet has grown exponentially. With the proliferation of online activities, data-driven systems, and interconnected devices, the need to protect sensitive information and digital infrastructure has never been greater. One of the most significant aspects of cybersecurity is safeguarding personal and confidential data. From financial transactions to healthcare records and personal communications, our digital lives are intertwined with valuable data that must be shielded from malicious actors. Breaches of data can have far-reaching consequences, including identity theft, financial loss, and privacy violations. Moreover, as critical infrastructure systems like power grids and transportation networks become increasingly reliant on digital controls, the potential for cyberattacks to disrupt essential services poses a significant threat to society. Cybersecurity is also vital for preserving national security, as governments and organizations store sensitive information related to defense, intelligence, and diplomacy. The rise of state-sponsored cyberattacks highlights the need for robust cybersecurity measures to protect against espionage and cyber warfare. The field of cybersecurity is a constant arms race, as cybercriminals continuously evolve their tactics and techniques. Staying ahead of these threats requires ongoing innovation and collaboration between cybersecurity experts, governments, and private enterprises. While technology has brought immense benefits to our lives, it also exposes us to new vulnerabilities. As we move forward in the digital age, prioritizing cybersecurity is essential to ensure the safety, privacy, and stability of our interconnected world. In conclusion, cybersecurity is a critical component of our digital lives, protecting personal data, critical infrastructure, and national security. It is an ongoing effort that requires vigilance, collaboration, and innovation to address evolving cyber threats and secure our increasingly interconnected world"

string_nine = "Remote work has emerged as a transformative force in the world of employment, reshaping traditional work structures and offering new opportunities and challenges for both employers and employees. The COVID-19 pandemic accelerated the adoption of remote work, but its impact is likely to endure long after the crisis has passed. One of the most significant impacts of remote work is the shift in the perception of work location. No longer bound by physical office spaces, employees can now collaborate and contribute from virtually anywhere with an internet connection. This newfound flexibility has the potential to democratize access to job opportunities, allowing individuals to work for companies or clients across geographic boundaries. However, it also raises concerns about work-life balance, as the boundaries between work and personal life blur. Remote work has also prompted a reevaluation of workplace dynamics. Employers are increasingly focusing on outcomes and productivity rather than traditional notions of hours spent in an office. This shift in mindset offers employees greater autonomy and flexibility in managing their work schedules. Additionally, remote work has reduced the need for extensive office spaces and commutes, contributing to environmental sustainability and cost savings for both organizations and individuals. However, it also poses challenges related to maintaining team cohesion, communication, and employee engagement in a virtual environment. The future of employment is likely to be characterized by a hybrid model, with a mix of remote and in-person work. Employers are exploring innovative ways to balance the benefits of remote work with the need for face-to-face interactions and collaboration. In conclusion, remote work has reshaped the landscape of employment, offering flexibility, reducing environmental impact, and redefining traditional work structures. While it presents opportunities for inclusivity and productivity, it also requires adaptation to address challenges related to work-life balance, communication, and employee engagement in a digital world. The future of employment will be shaped by how organizations and individuals navigate and embrace this evolving paradigm."


function removeNonAlpha(sentence){


    return sentence.replace(/[^a-zA-Z\s]/g, '');
}



function gatherUniqueWords(cur_string){



    cur_string = removeNonAlpha(cur_string);
    

    split_string = cur_string.split(/\s+/)
    // split the string

    for (i = 0; i < split_string.length; i++){
        if(unique_words.indexOf(split_string[i]) === -1){
            unique_words.push(split_string[i])
        }
    }
}


async function uploadWordList(){

    gatherUniqueWords(string_one);
    gatherUniqueWords(string_two);
    gatherUniqueWords(string_three);
    gatherUniqueWords(string_four);
    gatherUniqueWords(string_five);
    gatherUniqueWords(string_six);
    gatherUniqueWords(string_seven);
    gatherUniqueWords(string_eight);
    gatherUniqueWords(string_nine);


    console.log(unique_words.length);
    // Filter out empty words and remove non-alphabet characters
    let processed_words = unique_words
    .filter(word => word.length > 0) // Keeps words with length greater than 0
    .map(word => word.replace(/[^a-zA-Z]/g, ''));



    
    await clientDB.connect();
    let new_doc = {
        "words": processed_words
    }


    const main_db = clientDB.db("sample_passages")
    const Testing = main_db.collection("Testing");


    last_document = await Testing.countDocuments()

    if(last_document <= 0){
        // create the first document
        new_doc["version"] = 1;
    }
    else{
        new_doc["version"] = last_document + 1;
    }

    Testing.insertOne(new_doc).then(async () => {
        await clientDB.close();

    });
    
    
    return;

}


uploadWordList();